services:
  minecraft:
    build: .
    container_name: mc-fabric
    ports:
      - "2005:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21"
    volumes:
      - ./data:/data
    restart: unless-stopped
