services:
  minecraft:
    build: .
    container_name: FORGE
    ports:
      - "2005:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGEVERSION: "47.4.0"
      MEMORY: "8G"
      JVM_XX_OPTS: >
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=200
        -XX:+UnlockExperimentalVMOptions
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=30
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=8M
        -XX:G1ReservePercent=15
        -XX:InitiatingHeapOccupancyPercent=20
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:+PerfDisableSharedMem
        -Dusing.aikars.flags=true 
    volumes:
      - ./:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mc-health"]
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 5m
