services:
  minecraft:
    build: .
    container_name: Forge
    ports:
      - "2005:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGEVERSION: "47.4.0"
      MEMORY: "6G"
    volumes:
      - ./:/data
    restart: unless-stopped
