name: Update Minecraft Server on Push

on:
  push:
    branches:
      - main

jobs:
  restart-server:
    environment: desarrollo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restart Minecraft container over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd Desktop/minecraft-server-java-or-bedrock/
            git pull origin main
            docker restart FORGE
